/**
 * Complete Portugal municipality-to-district map.
 * All 308 municipalities of continental Portugal mapped to their district.
 *
 * Used to infer district from municipality when scrapers only extract concelho.
 */

const MUNICIPALITY_TO_DISTRICT = {
  // ── Viana do Castelo (10) ──
  'arcos de valdevez': 'Viana do Castelo',
  'caminha': 'Viana do Castelo',
  'melgaco': 'Viana do Castelo',
  'melgaço': 'Viana do Castelo',
  'moncao': 'Viana do Castelo',
  'monção': 'Viana do Castelo',
  'paredes de coura': 'Viana do Castelo',
  'ponte da barca': 'Viana do Castelo',
  'ponte de lima': 'Viana do Castelo',
  'valenca': 'Viana do Castelo',
  'valença': 'Viana do Castelo',
  'viana do castelo': 'Viana do Castelo',
  'vila nova de cerveira': 'Viana do Castelo',

  // ── Braga (14) ──
  'amares': 'Braga',
  'barcelos': 'Braga',
  'braga': 'Braga',
  'cabeceiras de basto': 'Braga',
  'celorico de basto': 'Braga',
  'esposende': 'Braga',
  'fafe': 'Braga',
  'guimaraes': 'Braga',
  'guimarães': 'Braga',
  'povoa de lanhoso': 'Braga',
  'póvoa de lanhoso': 'Braga',
  'terras de bouro': 'Braga',
  'vieira do minho': 'Braga',
  'vila nova de famalicao': 'Braga',
  'vila nova de famalicão': 'Braga',
  'vila verde': 'Braga',
  'vizela': 'Braga',

  // ── Porto (18) ──
  'amarante': 'Porto',
  'baiao': 'Porto',
  'baião': 'Porto',
  'felgueiras': 'Porto',
  'gondomar': 'Porto',
  'lousada': 'Porto',
  'maia': 'Porto',
  'marco de canaveses': 'Porto',
  'matosinhos': 'Porto',
  'pacos de ferreira': 'Porto',
  'paços de ferreira': 'Porto',
  'paredes': 'Porto',
  'penafiel': 'Porto',
  'porto': 'Porto',
  'povoa de varzim': 'Porto',
  'póvoa de varzim': 'Porto',
  'santo tirso': 'Porto',
  'trofa': 'Porto',
  'valongo': 'Porto',
  'vila do conde': 'Porto',
  'vila nova de gaia': 'Porto',

  // ── Vila Real (14) ──
  'alijo': 'Vila Real',
  'alijó': 'Vila Real',
  'boticas': 'Vila Real',
  'chaves': 'Vila Real',
  'mesao frio': 'Vila Real',
  'mesão frio': 'Vila Real',
  'mondim de basto': 'Vila Real',
  'montalegre': 'Vila Real',
  'murca': 'Vila Real',
  'murça': 'Vila Real',
  'peso da regua': 'Vila Real',
  'peso da régua': 'Vila Real',
  'ribeira de pena': 'Vila Real',
  'sabrosa': 'Vila Real',
  'santa marta de penaguiao': 'Vila Real',
  'santa marta de penaguião': 'Vila Real',
  'valpacos': 'Vila Real',
  'valpaços': 'Vila Real',
  'vila pouca de aguiar': 'Vila Real',
  'vila real': 'Vila Real',

  // ── Bragança (12) ──
  'alfandega da fe': 'Bragança',
  'alfândega da fé': 'Bragança',
  'braganca': 'Bragança',
  'bragança': 'Bragança',
  'carrazeda de ansiaes': 'Bragança',
  'carrazeda de ansiães': 'Bragança',
  'freixo de espada a cinta': 'Bragança',
  'freixo de espada à cinta': 'Bragança',
  'macedo de cavaleiros': 'Bragança',
  'miranda do douro': 'Bragança',
  'mirandela': 'Bragança',
  'mogadouro': 'Bragança',
  'torre de moncorvo': 'Bragança',
  'vila flor': 'Bragança',
  'vimioso': 'Bragança',
  'vinhais': 'Bragança',

  // ── Aveiro (19) ──
  'agueda': 'Aveiro',
  'águeda': 'Aveiro',
  'albergaria-a-velha': 'Aveiro',
  'anadia': 'Aveiro',
  'arouca': 'Aveiro',
  'aveiro': 'Aveiro',
  'castelo de paiva': 'Aveiro',
  'espinho': 'Aveiro',
  'estarreja': 'Aveiro',
  'ilhavo': 'Aveiro',
  'ílhavo': 'Aveiro',
  'mealhada': 'Aveiro',
  'murtosa': 'Aveiro',
  'oliveira de azemeis': 'Aveiro',
  'oliveira de azeméis': 'Aveiro',
  'oliveira do bairro': 'Aveiro',
  'ovar': 'Aveiro',
  'santa maria da feira': 'Aveiro',
  'sao joao da madeira': 'Aveiro',
  'são joão da madeira': 'Aveiro',
  'sever do vouga': 'Aveiro',
  'vagos': 'Aveiro',
  'vale de cambra': 'Aveiro',

  // ── Viseu (24) ──
  'armamar': 'Viseu',
  'carregal do sal': 'Viseu',
  'castro daire': 'Viseu',
  'cinfaes': 'Viseu',
  'cinfães': 'Viseu',
  'lamego': 'Viseu',
  'mangualde': 'Viseu',
  'moimenta da beira': 'Viseu',
  'mortagua': 'Viseu',
  'mortágua': 'Viseu',
  'nelas': 'Viseu',
  'oliveira de frades': 'Viseu',
  'penalva do castelo': 'Viseu',
  'penedono': 'Viseu',
  'resende': 'Viseu',
  'santa comba dao': 'Viseu',
  'santa comba dão': 'Viseu',
  'sao joao da pesqueira': 'Viseu',
  'são joão da pesqueira': 'Viseu',
  'sao pedro do sul': 'Viseu',
  'são pedro do sul': 'Viseu',
  'satao': 'Viseu',
  'sátão': 'Viseu',
  'sernancelhe': 'Viseu',
  'tabuaco': 'Viseu',
  'tabuaço': 'Viseu',
  'tarouca': 'Viseu',
  'tondela': 'Viseu',
  'vila nova de paiva': 'Viseu',
  'viseu': 'Viseu',
  'vouzela': 'Viseu',

  // ── Guarda (14) ──
  'aguiar da beira': 'Guarda',
  'almeida': 'Guarda',
  'celorico da beira': 'Guarda',
  'fig. de castelo rodrigo': 'Guarda',
  'figueira de castelo rodrigo': 'Guarda',
  'fornos de algodres': 'Guarda',
  'gouveia': 'Guarda',
  'guarda': 'Guarda',
  'manteigas': 'Guarda',
  'meda': 'Guarda',
  'pinhel': 'Guarda',
  'sabugal': 'Guarda',
  'seia': 'Guarda',
  'trancoso': 'Guarda',

  // ── Coimbra (17) ──
  'arganil': 'Coimbra',
  'cantanhede': 'Coimbra',
  'coimbra': 'Coimbra',
  'condeixa-a-nova': 'Coimbra',
  'figueira da foz': 'Coimbra',
  'gois': 'Coimbra',
  'góis': 'Coimbra',
  'lousa': 'Coimbra',
  'lousã': 'Coimbra',
  'mira': 'Coimbra',
  'miranda do corvo': 'Coimbra',
  'montemor-o-velho': 'Coimbra',
  'oliveira do hospital': 'Coimbra',
  'pampilhosa da serra': 'Coimbra',
  'penacova': 'Coimbra',
  'penela': 'Coimbra',
  'soure': 'Coimbra',
  'tabua': 'Coimbra',
  'tábua': 'Coimbra',
  'vila nova de poiares': 'Coimbra',

  // ── Castelo Branco (11) ──
  'belmonte': 'Castelo Branco',
  'castelo branco': 'Castelo Branco',
  'covilha': 'Castelo Branco',
  'covilhã': 'Castelo Branco',
  'fundao': 'Castelo Branco',
  'fundão': 'Castelo Branco',
  'idanha-a-nova': 'Castelo Branco',
  'oleiros': 'Castelo Branco',
  'penamacor': 'Castelo Branco',
  'proenca-a-nova': 'Castelo Branco',
  'proença-a-nova': 'Castelo Branco',
  'serta': 'Castelo Branco',
  'sertã': 'Castelo Branco',
  'vila de rei': 'Castelo Branco',
  'vila velha de rodao': 'Castelo Branco',
  'vila velha de ródão': 'Castelo Branco',

  // ── Leiria (16) ──
  'alcobaca': 'Leiria',
  'alcobaça': 'Leiria',
  'alvaiazere': 'Leiria',
  'alvaiázere': 'Leiria',
  'ansiao': 'Leiria',
  'ansião': 'Leiria',
  'batalha': 'Leiria',
  'bombarral': 'Leiria',
  'caldas da rainha': 'Leiria',
  'castanheira de pera': 'Leiria',
  'castanheira de pêra': 'Leiria',
  'figueiro dos vinhos': 'Leiria',
  'figueiró dos vinhos': 'Leiria',
  'leiria': 'Leiria',
  'marinha grande': 'Leiria',
  'nazare': 'Leiria',
  'nazaré': 'Leiria',
  'obidos': 'Leiria',
  'óbidos': 'Leiria',
  'pedrogao grande': 'Leiria',
  'pedrógão grande': 'Leiria',
  'peniche': 'Leiria',
  'pombal': 'Leiria',
  'porto de mos': 'Leiria',
  'porto de mós': 'Leiria',

  // ── Lisboa (16) ──
  'alenquer': 'Lisboa',
  'amadora': 'Lisboa',
  'arruda dos vinhos': 'Lisboa',
  'azambuja': 'Lisboa',
  'cadaval': 'Lisboa',
  'cascais': 'Lisboa',
  'lisboa': 'Lisboa',
  'loures': 'Lisboa',
  'lourinha': 'Lisboa',
  'lourinhã': 'Lisboa',
  'mafra': 'Lisboa',
  'odivelas': 'Lisboa',
  'oeiras': 'Lisboa',
  'sintra': 'Lisboa',
  'sobral de monte agraco': 'Lisboa',
  'sobral de monte agraço': 'Lisboa',
  'torres vedras': 'Lisboa',
  'vila franca de xira': 'Lisboa',

  // ── Santarém (21) ──
  'abrantes': 'Santarém',
  'almeirim': 'Santarém',
  'alpiarca': 'Santarém',
  'alpiarça': 'Santarém',
  'benavente': 'Santarém',
  'cartaxo': 'Santarém',
  'chamusca': 'Santarém',
  'constancia': 'Santarém',
  'constância': 'Santarém',
  'coruche': 'Santarém',
  'entroncamento': 'Santarém',
  'ferreira do zezere': 'Santarém',
  'ferreira do zêzere': 'Santarém',
  'golega': 'Santarém',
  'golegã': 'Santarém',
  'macao': 'Santarém',
  'mação': 'Santarém',
  'ourém': 'Santarém',
  'ourem': 'Santarém',
  'rio maior': 'Santarém',
  'salvaterra de magos': 'Santarém',
  'santarem': 'Santarém',
  'santarém': 'Santarém',
  'sardoal': 'Santarém',
  'tomar': 'Santarém',
  'torres novas': 'Santarém',
  'vila nova da barquinha': 'Santarém',

  // ── Setúbal (13) ──
  'alcacer do sal': 'Setúbal',
  'alcácer do sal': 'Setúbal',
  'alcochete': 'Setúbal',
  'almada': 'Setúbal',
  'barreiro': 'Setúbal',
  'grandola': 'Setúbal',
  'grândola': 'Setúbal',
  'moita': 'Setúbal',
  'montijo': 'Setúbal',
  'palmela': 'Setúbal',
  'santiago do cacem': 'Setúbal',
  'santiago do cacém': 'Setúbal',
  'seixal': 'Setúbal',
  'sesimbra': 'Setúbal',
  'setubal': 'Setúbal',
  'setúbal': 'Setúbal',
  'sines': 'Setúbal',

  // ── Portalegre (15) ──
  'alter do chao': 'Portalegre',
  'alter do chão': 'Portalegre',
  'arronches': 'Portalegre',
  'avis': 'Portalegre',
  'campo maior': 'Portalegre',
  'castelo de vide': 'Portalegre',
  'crato': 'Portalegre',
  'elvas': 'Portalegre',
  'fronteira': 'Portalegre',
  'gaviao': 'Portalegre',
  'gavião': 'Portalegre',
  'marvao': 'Portalegre',
  'marvão': 'Portalegre',
  'monforte': 'Portalegre',
  'nisa': 'Portalegre',
  'ponte de sor': 'Portalegre',
  'portalegre': 'Portalegre',
  'sousel': 'Portalegre',

  // ── Évora (14) ──
  'alandroal': 'Évora',
  'arraiolos': 'Évora',
  'borba': 'Évora',
  'estremoz': 'Évora',
  'evora': 'Évora',
  'évora': 'Évora',
  'montemor-o-novo': 'Évora',
  'mora': 'Évora',
  'mourao': 'Évora',
  'mourão': 'Évora',
  'portel': 'Évora',
  'redondo': 'Évora',
  'reguengos de monsaraz': 'Évora',
  'vendas novas': 'Évora',
  'viana do alentejo': 'Évora',
  'vila vicosa': 'Évora',
  'vila viçosa': 'Évora',

  // ── Beja (14) ──
  'aljustrel': 'Beja',
  'almodovar': 'Beja',
  'almodôvar': 'Beja',
  'alvito': 'Beja',
  'barrancos': 'Beja',
  'beja': 'Beja',
  'castro verde': 'Beja',
  'cuba': 'Beja',
  'ferreira do alentejo': 'Beja',
  'mertola': 'Beja',
  'mértola': 'Beja',
  'moura': 'Beja',
  'odemira': 'Beja',
  'ourique': 'Beja',
  'serpa': 'Beja',
  'vidigueira': 'Beja',

  // ── Faro (16) ──
  'albufeira': 'Faro',
  'alcoutim': 'Faro',
  'aljezur': 'Faro',
  'castro marim': 'Faro',
  'faro': 'Faro',
  'lagoa': 'Faro',
  'lagos': 'Faro',
  'loule': 'Faro',
  'loulé': 'Faro',
  'monchique': 'Faro',
  'olhao': 'Faro',
  'olhão': 'Faro',
  'portimao': 'Faro',
  'portimão': 'Faro',
  'sao bras de alportel': 'Faro',
  'são brás de alportel': 'Faro',
  'silves': 'Faro',
  'tavira': 'Faro',
  'vila do bispo': 'Faro',
  'vila real de santo antonio': 'Faro',
  'vila real de santo antónio': 'Faro',
};

/**
 * Normalize a string for lookup: lowercase + strip diacritics.
 */
function normalizeKey(str) {
  if (typeof str !== 'string') return '';
  return str
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .toLowerCase();
}

/**
 * Get the district name for a given Portuguese municipality.
 * Handles accented and non-accented input.
 *
 * @param {string} municipality - Municipality name (e.g. "Ponte de Lima", "ponte de lima")
 * @returns {string|null} District name with proper casing, or null if not found
 */
function getDistrictForMunicipality(municipality) {
  if (!municipality || typeof municipality !== 'string') return null;

  // Try exact lowercase match first (handles accented keys)
  const lower = municipality.trim().toLowerCase();
  if (MUNICIPALITY_TO_DISTRICT[lower]) {
    return MUNICIPALITY_TO_DISTRICT[lower];
  }

  // Try normalized (stripped diacritics) match
  const normalized = normalizeKey(municipality);
  if (MUNICIPALITY_TO_DISTRICT[normalized]) {
    return MUNICIPALITY_TO_DISTRICT[normalized];
  }

  return null;
}

module.exports = { getDistrictForMunicipality, MUNICIPALITY_TO_DISTRICT };
